title: ToothLess Graffiti
description: Toothless' Personal Blog
author: ToothLess
logo: /toothlessdev.github.io/static/img/avatar.jpg
github: https://github.com/toothlessdev
about: Developer

baseurl: "https://toothlessdev.github.io"
url: "https://toothlessdev.github.io"

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: ["Dev", "Algorithm"]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
