name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Cache optimized images
        uses: actions/cache@v4
        with:
          path: |
            contents/posts/**/img/**/*.webp
            contents/posts/**/img/**/*.jpeg
          key: optimized-images-${{ hashFiles('contents/posts/**/img/**/*.{jpg,jpeg,png}') }}
          restore-keys: |
            optimized-images-

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build with VitePress
        run: npm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  update-pr-body:
    name: Update PR Body
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != '' && contains(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Find Pull Request Number
        id: find_pr
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*Merge pull request #\([0-9]\+\).*/\1/p')
          if [ -z "$PR_NUMBER" ]; then
            echo "Could not find PR number in commit message."
            exit 1
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Update Pull Request Body
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.find_pr.outputs.PR_NUMBER }}
          PAGE_URL: ${{ needs.deploy.outputs.page_url }}
        run: |
          export BODY=$(gh pr view $PR_NUMBER --json body -q .body)
          export HEADER="🚀 **배포 완료!**\n**배포된 사이트:** [${PAGE_URL}](${PAGE_URL})"
          gh pr edit $PR_NUMBER --body-file - <<EOF
          ${HEADER}

          ---

          ${BODY}
          EOF
